
Strand = "TAGAGTCGGGCCTCTCGGATAGGTAGTAATTGGGGTCCGGGTAATAGGTGTTCCCAGACCGCCCACGTCCCCTAGACCGGAGAGTTATTATGGATTGATATGCAACGAGATTTCCCGGCCACTCACTTATTTTTCTCATATGGGGGGAGACCACTTTTTACGCGAGATCTTCGTTGAAGTATTAACGAGTACGCGACATTAATGATCATCAGTGCGCGGCTGGGCGTTTTTCTGCCGGGTCGTAGATGTGGAGAAACGGCAACTAGTAGAATTGGAGGGGAGGTTGCAGTAAGAGTGGGAAACTCGTGTAACACGCCTCAGCAAAGAACAGACATCCTTAAGATGTCCGGTTCCAACTAGACCTCCTTCGACGGCTTACAGATAGTCAGCTTGCAACTAGAACGAAACAATTGAAACTACTCCAGCGATACCATCCATGGCATACGTACTGCGCCCCTTACATCCAATTAAATCATATTCAGCAACACGAACGTGTGTCATACGACTGAGAGATCTGAAAGTCTCGCGAGATATCTGTGAGACCCGCGGACGCTTGAACTTTCCGCAGGGCAGCCCAGATTGTTGCCAATAATATCCGCCTACTCGGTTTCCGACGCGCCAGAGGATAAGGCGGTCGGCCCCGTGGTCGTTTAAGTTACAGTACGAGGCTACGGTTTGTGAACTGGCTTGGGTTATATCTGCACTGGGGATACCCTAGGAATAAGTGTGCGCTGCCCTAAGATATCTCAAGTCTTTCCCCACAAGAGTACCAGATGAGGTGAACGGAAGCACCCATTGTCCTGCATCAATGTCGGCACTGAGGGGAGACCAGTCGCCGGGTCGATTTAGCTAAACAGAAGACTTTAGGATATGTCCGTCAGGTAGGAACGACCGAAGATGTTCTTGACGTGTCGAAGGCCAGTAGTGTAACACAACTCCAAACCAAATGCTGATGCCCCACAATGAATCACACTGCAGAACTGTTGGACATA"
StrandAmounts = {
    "A": 0,
    "C": 0,
    "G": 0,
    "T": 0
}

for x in Strand:
    if x == "A":
        StrandAmounts["A"] = StrandAmounts.get("A", 0) + 1
    elif x == "C":
        StrandAmounts["C"] = StrandAmounts.get("C", 0) + 1
    elif x == "G":
        StrandAmounts["G"] = StrandAmounts.get("G", 0) + 1
    elif x == "T":
        StrandAmounts["T"] = StrandAmounts.get("T", 0) + 1

print(StrandAmounts["A"], StrandAmounts["C"], StrandAmounts["G"], StrandAmounts["T"])